# Generated by Django 4.2.3 on 2023-07-31 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_category_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={},
        ),
    ]
